version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres_shared
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SSHiverMeTimbers
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
