services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}