# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSHmealDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 776)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 600, 780))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(128, 194, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.colourWidget = QtWidgets.QWidget(self.widget)
        self.colourWidget.setGeometry(QtCore.QRect(0, 0, 600, 780))
        self.colourWidget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.091, y1:0.101636, x2:0.991379, y2:0.977, stop:0 rgba(128, 194, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.colourWidget.setObjectName("colourWidget")
        self.lblSSHmeals = QtWidgets.QLabel(self.colourWidget)
        self.lblSSHmeals.setGeometry(QtCore.QRect(60, 90, 461, 101))
        self.lblSSHmeals.setStyleSheet("font: 75 48pt \"Georgia\";\n"
"color:rgba(0, 51, 102, 1)")
        self.lblSSHmeals.setObjectName("lblSSHmeals")
        self.ingredientsButton = QtWidgets.QPushButton(self.colourWidget)
        self.ingredientsButton.setGeometry(QtCore.QRect(140, 280, 291, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setStrikeOut(False)
        self.ingredientsButton.setFont(font)
        self.ingredientsButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ingredientsButton.setAutoFillBackground(False)
        self.ingredientsButton.setStyleSheet("border-radius:50px;\n"
"border-color:rgba(255, 215, 0, 1);\n"
"background-color:rgba(0, 102, 204, 1);\n"
"font: 75 24pt \"Verdana\";\n"
"color: rgb(255,255,255);\n"
"alternate-background-color: rgba(0, 102, 102, 1);")
        self.ingredientsButton.setObjectName("ingredientsButton")
        self.recipeButton = QtWidgets.QPushButton(self.colourWidget)
        self.recipeButton.setGeometry(QtCore.QRect(140, 480, 291, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setStrikeOut(False)
        self.recipeButton.setFont(font)
        self.recipeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.recipeButton.setAutoFillBackground(False)
        self.recipeButton.setStyleSheet("border-radius:50px;\n"
"border-color:rgba(255, 215, 0, 1);\n"
"background-color:rgba(0, 102, 204, 1);\n"
"font: 75 24pt \"Verdana\";\n"
"color: rgb(255,255,255);\n"
"alternate-background-color: rgba(0, 102, 102, 1);")
        self.recipeButton.setObjectName("recipeButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblSSHmeals.setText(_translate("Dialog", "SSH MEALS"))
        self.ingredientsButton.setText(_translate("Dialog", "Ingredients"))
        self.recipeButton.setText(_translate("Dialog", "Recipe\n"
"Suggestions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
